"""Emit the LaTeX for the protocol-inflation table from leakage_ablation_results.csv.

Generated rather than transcribed so every number in main_jasmp.tex traces to the
committed CSV. Run after leakage_ablation.py:

    python make_leakage_table.py            # writes tab_leakage.tex, prints a summary
"""
import sys
import pandas as pd

CSV = sys.argv[1] if len(sys.argv) > 1 else "leakage_ablation_results.csv"
OUT = sys.argv[2] if len(sys.argv) > 2 else "tab_leakage.tex"

LABEL = {
    "P0_speaker_disjoint":     ("P0", "speaker-disjoint holdout", "none"),
    "P1_random_holdout":       ("P1", "random holdout",           "M2"),
    "P2_random_kfold":         ("P2", "random 5-fold",            "M2"),
    "P3_presplit_smote_kfold": ("P3", "pre-split SMOTE + 5-fold",  "M1+M2"),
}
ORDER = list(LABEL)

df = pd.read_csv(CSV)
seeds = sorted(df["seed"].unique())

# Per-seed mean over folds first, so each seed contributes once to the spread.
per_seed = (df.groupby(["protocol", "features", "model", "seed"])[["accuracy", "eer"]]
              .mean().reset_index())
agg = (per_seed.groupby(["protocol", "features", "model"])[["accuracy", "eer"]]
       .agg(["mean", "std"]).reset_index())
agg.columns = ["protocol", "features", "model", "acc", "acc_sd", "eer", "eer_sd"]

rows, best = [], {}
for proto in ORDER:
    sub = agg[agg["protocol"] == proto]
    if sub.empty:
        continue
    b = sub.loc[sub["acc"].idxmax()]          # the number a paper would headline
    best[proto] = b
    tag, desc, mech = LABEL[proto]
    rows.append(
        f"{tag} & {desc} & {mech} & "
        f"{b['acc']:.2f}\\,$\\pm$\\,{b['acc_sd']:.2f} & "
        f"{b['eer']:.2f}\\,$\\pm$\\,{b['eer_sd']:.2f} & "
        f"{b['model']} \\\\")

body = "\n".join(rows)
p0 = best["P0"] if "P0" in best else best[ORDER[0]]
tex = f"""% GENERATED by make_leakage_table.py from {CSV} -- do not edit by hand.
\\begin{{table}}[t]
\\centering
\\caption{{Protocol inflation measured on our own benchmark. Identical features and
identical classifiers throughout; only the split and the resampling change. Each
cell is the best-accuracy configuration for that protocol---the number a paper
following that protocol would report---as mean\\,$\\pm$\\,s.d.\\ over
{len(seeds)} seeds. P0$\\to$P1 isolates M2 at a matched train fraction; all three
leaky protocols sit far above P0 on both metrics. See text for the P2 vs.\\ P3
comparison, which is not a clean isolation of M1.}}
\\label{{tab:leakage}}
\\small\\setlength{{\\tabcolsep}}{{4.5pt}}
\\begin{{tabular}}{{@{{}}llllll@{{}}}}
\\toprule
 & Protocol & Mech. & Accuracy (\\%) & EER (\\%) & Best model \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
open(OUT, "w").write(tex)

print(f"seeds: {seeds}\nwrote {OUT}\n")
for proto in ORDER:
    if proto not in best:
        continue
    b = best[proto]
    d_acc = b["acc"] - p0["acc"]
    print(f"  {LABEL[proto][0]}  acc {b['acc']:6.2f} +-{b['acc_sd']:4.2f}  "
          f"EER {b['eer']:5.2f} +-{b['eer_sd']:4.2f}  "
          f"(delta acc vs P0 {d_acc:+6.2f})  [{b['model']} / {b['features']}]")

# Matched-pair contrasts: P0->P1 shares a train fraction, P2->P3 shares the protocol.
print("\nmatched contrasts (best-accuracy config per arm):")
if "P0_speaker_disjoint" in best and "P1_random_holdout" in best:
    a, b_ = best["P0_speaker_disjoint"], best["P1_random_holdout"]
    print(f"  M2 alone  P0->P1: acc {a['acc']:.2f} -> {b_['acc']:.2f} "
          f"({b_['acc']-a['acc']:+.2f}), EER {a['eer']:.2f} -> {b_['eer']:.2f} "
          f"({b_['eer']-a['eer']:+.2f})")
if "P2_random_kfold" in best and "P3_presplit_smote_kfold" in best:
    a, b_ = best["P2_random_kfold"], best["P3_presplit_smote_kfold"]
    print(f"  +M1      P2->P3: acc {a['acc']:.2f} -> {b_['acc']:.2f} "
          f"({b_['acc']-a['acc']:+.2f}), EER {a['eer']:.2f} -> {b_['eer']:.2f} "
          f"({b_['eer']-a['eer']:+.2f})")
